---
title: "ENDES_TBM_2019"
author: "Carlos Ballon-Salcedo"
format: html
editor: source
execute:
  echo: false
  warning: false
  message: false
  error: false
  include: true
  results: hide
  cache: false
  fig_caption: true
  fig_width: 6
  fig_height: 4
  out.width: "100%"
  out.extra: |
    class="img-responsive"
    style="display:block; margin-left:auto; margin-right:auto;"
---

# Load packages

```{r}
pacman::p_load(
  rio,
  here,
  tidyverse,
  survey,
  gtsummary,
  finalfit,
  flextable,
  bstfun,
  haven, 
  janitor,
  labelled,
  naniar,
  rfextras,
  epiDisplay,
  Hmisc)

#source(here::here("scripts", "dictionary.R"))
rfextras::load_scripts()
```

# Import data (Carlos)

```{r}
# 
individual_data <- rio::import(here::here("data", "2024", "RECH1_2024.dta"))

home_data <- rio::import(here::here("data", "2024", "RECH0_2024.dta"))

dwelling_data <- rio::import(here::here("data", "2024", "RECH23_2024.dta"))
```

```{r}
woman_data_1 <- rio::import(here::here("data", "2024", "RECH5_2024.dta"))

woman_data_2 <- rio::import(here::here("data", "2024", "REC0111_2024.dta"))

woman_data_3 <- rio::import(here::here("data", "2024", "REC41_2024.dta"))

woman_data_4 <- rio::import(here::here("data", "2024", "REC44_2024.dta"))

woman_data_5 <- rio::import(here::here("data", "2024", "RE223132_2024.dta"))
```

```{r}
children_data_1 <- rio::import(here::here("data", "2024", "RECH6_2024.dta"))

children_data_2 <- rio::import(here::here("data", "2024", "REC44_2024.dta"))

children_data_3 <- rio::import(here::here("data", "2024", "REC43_2024.dta"))
```

```{r}
health_data <- rio::import(here::here("data", "2024", "CSALUD01_2024.dta"))
```

# Process data (Carlos)

## Normalization of identifiers

```{r}
# Individual data
individual_data <- individual_data |> 
  dplyr::mutate(QSNUMERO = HVIDX)

# Woman data
woman_data_1 <- woman_data_1 |> 
  dplyr::mutate(QSNUMERO = HA0)

woman_data_2 <- woman_data_2 |>
  dplyr::mutate(
    QSNUMERO = str_sub(CASEID, -2, -1),
    QSNUMERO = as.numeric(QSNUMERO))

woman_data_3 <- woman_data_3 |>
  dplyr::mutate(
    HHID = str_sub(CASEID, 1, str_length(CASEID) - 3),
    QSNUMERO = str_sub(CASEID, -2, -1),
    QSNUMERO = as.numeric(QSNUMERO)
  )

woman_data_4 <- woman_data_4 |>
  dplyr::mutate(
    HHID = str_sub(CASEID, 1, str_length(CASEID) - 3),
    QSNUMERO = str_sub(CASEID, -2, -1),
    QSNUMERO = as.numeric(QSNUMERO)
  )

woman_data_5 <- woman_data_5 |>
  dplyr::mutate(
    HHID = str_sub(CASEID, 1, str_length(CASEID) - 3),
    QSNUMERO = str_sub(CASEID, -2, -1),
    QSNUMERO = as.numeric(QSNUMERO)
  )

# Children data
children_data_1 <- children_data_1 |>
  dplyr::mutate(
    HW1 = HC1,
    HW2 = HC2,
    HW3 = HC3,
    HW53 = HC53,
    QSNUMERO = HC60
  ) |>
  dplyr::filter(HC13 == 0) # Filtramos a los ni単os medidos

children_data_2 <- children_data_2 |>
  dplyr::mutate(
    HHID = str_sub(CASEID, 1, str_length(CASEID) - 3),
    QSNUMERO = str_sub(CASEID, -2, -1),
    QSNUMERO = as.numeric(QSNUMERO)
  ) |>
  dplyr::filter(HW13 == 0) # Filtramos a los ni単os medidos

children_data_3 <- children_data_3 |>
  dplyr::mutate(
    HHID = str_sub(CASEID, 1, str_length(CASEID) - 3),
    QSNUMERO = str_sub(CASEID, -2, -1),
    QSNUMERO = as.numeric(QSNUMERO)
  )
```

## Join dataframes

```{r}
# Join mother data
woman_data <- woman_data_1 |>
  dplyr::left_join(woman_data_2, by = c("HHID", "QSNUMERO")) |>
  dplyr::left_join(woman_data_4, by = c("HHID", "QSNUMERO")) |>
  dplyr::left_join(woman_data_5, by = c("HHID", "QSNUMERO"))

# Join children data
children_data <- children_data_1 |>
  dplyr::left_join(children_data_2, by = c("HHID", "QSNUMERO", "HW1", "HW2", "HW3")) |>
  dplyr::left_join(children_data_3, by = c("HHID", "QSNUMERO")) |>
  dplyr::rename(MIDX = HWIDX)

# Join children data with mother data
children_mother_data <- children_data |>
  dplyr::left_join(woman_data_3, by = c("HHID", "QSNUMERO", "MIDX"))

# Join home data with dwelling data
home_dwelling_data <- home_data |>
  dplyr::left_join(dwelling_data, by = "HHID")

# Join children/mother data with individual data
children_mother_individual_data <- children_mother_data |>
  dplyr::left_join(individual_data, by = c("HHID","QSNUMERO"))

# Join home/dwelling/individual data with mother data
pre_data <- children_mother_individual_data |>
  dplyr::left_join(woman_data, by = c("HHID","QSNUMERO"))

# Join home/dwelling/individual/mother data with health data
pre_data_1 <- pre_data |> 
  dplyr::left_join(health_data, by = c("HHID","QSNUMERO"))

# Join all
endestc <- pre_data_1 |>
  dplyr::left_join(home_dwelling_data, by = 'HHID')

# Clean names
# endestc <- janitor::clean_names(endestc)

# haven::write_dta(endestc, here::here("data", "endestc.dta"))

# n=19968
```

## Variable selection

```{r}
endes_dbm_tbm <- endestc |> dplyr::filter(HA54 != 1 | is.na(HA54)) # Excluyo embarazadas

# n=19537
```

## Non-plausible values

```{r}
data_anemia_2024 <- endes_dbm_tbm |>
  dplyr::mutate(
    HC70 = case_when(
      HC70 > 500  ~ NA_real_,
      HC70 < -500 ~ NA_real_,
      HC70 >= 9996 ~ NA_real_,
      TRUE ~ HC70
    ),
    HC72 = case_when(
      HC72 > 500  ~ NA_real_,
      HC72 < -500 ~ NA_real_,
      HC72 >= 9996 ~ NA_real_,
      TRUE ~ HC72
    ),
    HC71 = case_when(
      HC71 > 500  ~ NA_real_,
      HC71 < -500 ~ NA_real_,
      HC71 >= 9996 ~ NA_real_,
      TRUE ~ HC71
    ),
    bmi_mother_1 = (HA2 / 10) / ((HA3 / 10)^2) * 10000,
    bmi_mother_1 = case_when(
      bmi_mother_1 > 60  ~ NA_real_,
      bmi_mother_1 < 16 ~ NA_real_,
      TRUE ~ bmi_mother_1
    ),
    
    HA56 = case_when(
      HA56 > 900 ~ NA_real_,
      TRUE ~ HA56
    ),
    
    HC56 = case_when(
      HC56 > 900 ~ NA_real_,
      TRUE ~ HC56
    )
  ) |>
  dplyr::filter(
    !is.na(HC70),
    !is.na(HC72),
    !is.na(HC71),
    !is.na(bmi_mother_1)
  )

# n=18476

data_anemia_2024 <- data_anemia_2024 |> 
  dplyr::select(-ends_with(".x"), -ends_with(".y"))

haven::write_dta(data_anemia_2024, here::here("data", "2024", "data_anemia_2024_n31172.dta"))
```

```{r}
# Excluyo a hijos mayores
data_anemia_2024 <- data_anemia_2024 |>
  dplyr::group_by(HHID) |>
  dplyr::slice_min(HC1, with_ties = TRUE) |>
  dplyr::ungroup()

# n=16419

data_anemia_2024 <- data_anemia_2024 |> 
  dplyr::select(-ends_with(".x"), -ends_with(".y"))

haven::write_dta(data_anemia_2024, here::here("data", "2024", "data_anemia_2024_n16419.dta"))
```

```{r}
#| eval: false
#| include: false
summary(endes_dbm_tbm$age_mother)
summary(endes_dbm_tbm$bmi_mother)
sum(is.na(endes_dbm_tbm$sd_height_age_child))
sum(is.na(endes_dbm_tbm$HC71))
lapply(endes_dbm_tbm, function(x) sum(is.na(x)))

```

# Import data (Rodrigo)

```{r}
woman_data_1 <- rio::import(here::here("data", "2024", "RECH5_2024.dta"))

woman_data_2 <- rio::import(here::here("data", "2024", "REC0111_2024.dta"))

woman_data_3 <- rio::import(here::here("data", "2024", "REC91_2024.dta"))

woman_data_4 <- rio::import(here::here("data", "2024", "REC41_2024.dta"))

children_data_1 <- rio::import(here::here("data", "2024", "RECH6_2024.dta"))

children_data_2 <- rio::import(here::here("data", "2024", "RECH4_2024.dta"))

children_data_3 <- rio::import(here::here("data", "2024", "REC21_2024.dta"))

children_data_4 <- rio::import(here::here("data", "2024", "REC43_2024.dta"))

children_data_5 <- rio::import(here::here("data", "2024", "REC42_2024.dta"))

children_data_6 <- rio::import(here::here("data", "2024", "REC44_2024.dta"))

individual_data <- rio::import(here::here("data", "2024", "RECH1_2024.dta"))

home_data <- rio::import(here::here("data", "2024", "RECH0_2024.dta"))

dwelling_data <- rio::import(here::here("data", "2024", "RECH23_2024.dta"))

health_data <- rio::import(here::here("data", "2024", "CSALUD01_2024.dta"))

development_child <- rio::import(here::here("data", "2024", "DIT_2024.dta"))
```

# Process data (Rodrigo)

## Normalization of identifiers

```{r}
# Individual data
individual_data <- individual_data |> 
  dplyr::mutate(QSNUMERO = HVIDX)

# Woman data
woman_data_1 <- woman_data_1 |> 
  dplyr::mutate(QSNUMERO = HA0)

woman_data_2 <- woman_data_2 |>
  dplyr::mutate(
    QSNUMERO = str_sub(CASEID, -2, -1),
    QSNUMERO = as.numeric(QSNUMERO))

woman_data_3 <- woman_data_3 |>
  dplyr::mutate(
    HHID = str_sub(CASEID, 1, str_length(CASEID) - 3),
    QSNUMERO = str_sub(CASEID, -2, -1),
    QSNUMERO = as.numeric(QSNUMERO)
  )

woman_data_4 = woman_data_4 |>
  dplyr::mutate(
    HHID = str_sub(CASEID, 1, str_length(CASEID) - 3),
    QSNUMERO = str_sub(CASEID, -2, -1),
    QSNUMERO = as.numeric(QSNUMERO)
  )

# Children data
children_data_1 <- children_data_1 |>
  dplyr::mutate(
    HW1 = HC1,
    HW2 = HC2,
    HW3 = HC3,
    HW53 = HC53,
    QSNUMERO = HC60
  ) |>
  dplyr::filter(HC13 == 0) # Filtramos a los ni単os medidos

children_data_2 <- children_data_2 |>
  dplyr::mutate(
    QSNUMERO = IDXH4
  )

children_data_3 <- children_data_3 |>
  dplyr::mutate(
    HHID = str_sub(CASEID, 1, str_length(CASEID) - 3),
    QSNUMERO = str_sub(CASEID, -2, -1),
    QSNUMERO = as.numeric(QSNUMERO)
  )

children_data_4 <- children_data_4 |>
  dplyr::mutate(
    HHID = str_sub(CASEID, 1, str_length(CASEID) - 3),
    QSNUMERO = str_sub(CASEID, -2, -1),
    QSNUMERO = as.numeric(QSNUMERO)
  )

children_data_5 <- children_data_5 |>
  dplyr::mutate(
    HHID = str_sub(CASEID, 1, str_length(CASEID) - 3),
    QSNUMERO = str_sub(CASEID, -2, -1),
    QSNUMERO = as.numeric(QSNUMERO)
  )

children_data_6 <- children_data_6 |>
  dplyr::mutate(
    HHID = str_sub(CASEID, 1, str_length(CASEID) - 3),
    QSNUMERO = str_sub(CASEID, -2, -1),
    QSNUMERO = as.numeric(QSNUMERO)
  ) |>
  dplyr::filter(HW13 == 0) # Filtramos a los ni単os medidos

development_child <- development_child |>
  dplyr::mutate(
    HHID = str_sub(CASEID, 1, str_length(CASEID) - 3),
    QSNUMERO = str_sub(CASEID, -2, -1),
    QSNUMERO = as.numeric(QSNUMERO)
  )
```

## Join dataframes

```{r}
# Join mother data
woman_data <- woman_data_1 |>
  dplyr::left_join(woman_data_2, by = c("HHID", "QSNUMERO")) |>
  dplyr::left_join(woman_data_3, by = c("HHID", "QSNUMERO"))

# Join children data
children_data <- children_data_1 |>
  dplyr::left_join(children_data_2, by = c("HHID", "QSNUMERO")) |>
  dplyr::left_join(children_data_3, by = c("HHID", "QSNUMERO")) |>
  dplyr::left_join(children_data_4, by = c("HHID", "QSNUMERO")) |>
  dplyr::left_join(children_data_5, by = c("HHID", "QSNUMERO")) |>
  dplyr::left_join(children_data_6, by = c("HHID", "QSNUMERO")) |>
  dplyr::rename(MIDX = HWIDX)

# Join children data with mother data
children_mother_data <- children_data |>
  dplyr::left_join(woman_data_4, by = c("HHID", "QSNUMERO", "MIDX"))

# Join home data with dwelling data
home_dwelling_data <- home_data |>
  dplyr::left_join(dwelling_data, by = "HHID")

# Join children/mother data with individual data
children_mother_individual_data <- children_mother_data |>
  dplyr::left_join(individual_data, by = c("HHID", "QSNUMERO"))

# Join home/dwelling/individual data with mother data
pre_data <- children_mother_individual_data |>
  dplyr::left_join(woman_data, by = c("HHID","QSNUMERO"))

# Join home/dwelling/individual/mother data with health data
pre_data_1 <- pre_data |> 
  dplyr::left_join(health_data, by = c("HHID", "QSNUMERO"))

# Join children/mother/individual data with development child data
pre_data_2 <- pre_data_1 |>
  dplyr::left_join(development_child, "HHID", "QSNUMERO")

# Join all
data_anemia_2024 <- pre_data_2 |>
  dplyr::left_join(home_dwelling_data, by = 'HHID')

# Clean names
# endestc <- janitor::clean_names(endestc)

data_anemia_2024_1 <- data_anemia_2024 |> 
  dplyr::select(-ends_with(".x"), -ends_with(".y"))


# haven::write_dta(data_anemia_2024_1, here::here("data", "data_anemia_2024.dta"))
```

```{r}
data_anemia_2024 <- data_anemia_2024 |>
  dplyr::mutate(
    HC7 = case_when(
      HC7 >= 9990 ~ NA_real_,
      TRUE ~ HC7
    ))

a <- children_data_1 |>
  select(HC70) |>
  dplyr::mutate(
    HC70 = case_when(
      # HC70 > 500  ~ NA_real_,
      # HC70 < -500 ~ NA_real_,
      HC70 >= 9996 ~ NA_real_,
      TRUE ~ HC70
    ))

a
```
